// Generated by CoffeeScript 1.10.0
(function() {
  var addPx, boxes, bufferSize, calFullHeight, calHeight, calWidth, generateConvert, lineWidth, loadTemplate, metrics, selectedBox, templates;

  lineWidth = 50;

  bufferSize = 75;

  calWidth = 4200;

  calFullHeight = 3300;

  calHeight = calFullHeight - bufferSize;

  selectedBox = null;

  metrics = null;


  /*
  +---------+----------+
  |         |          |
  |         |    1     |
  |         +-----+----+
  |    0    |  3  |    |
  |         +--+--+    |
  |         |  |  | 2  |
  |         | 4|5 |    |
  +---------+--+--+----+
   */

  templates = [];

  boxes = [];

  boxes[0] = {
    top: 0,
    left: 0,
    width: 2000,
    height: calHeight
  };

  boxes[1] = {
    top: 0,
    left: boxes[0].width + lineWidth
  };

  boxes[1].width = calWidth - boxes[1].left;

  boxes[1].height = Math.round(boxes[1].width * 0.75);

  boxes[2] = {
    top: boxes[1].height + lineWidth,
    width: 945
  };

  boxes[2].height = calHeight - boxes[2].top;

  boxes[2].left = calWidth - boxes[2].width;

  boxes[3] = {
    top: boxes[2].top,
    left: boxes[1].left,
    width: calWidth - boxes[0].width - boxes[2].width - 2 * lineWidth,
    height: 756
  };

  boxes[4] = {
    top: boxes[1].height + boxes[3].height + 2 * lineWidth,
    left: boxes[3].left,
    width: 560
  };

  boxes[4].height = calHeight - boxes[4].top;

  boxes[5] = {
    top: boxes[4].top,
    left: boxes[4].left + boxes[4].width + lineWidth,
    width: calWidth - boxes[0].width - boxes[4].width - boxes[2].width - 3 * lineWidth,
    height: boxes[4].height
  };

  templates.push(boxes);

  templates.push([
    {
      top: 0,
      left: 0,
      width: calWidth,
      height: calHeight
    }
  ]);

  generateConvert = function() {
    var f, k;
    return ("convert -size " + calWidth + "x" + calFullHeight + " xc:black ") + ((function() {
      var results;
      results = [];
      for (k in metrics) {
        f = metrics[k];
        results.push("\\( " + f.name + " -crop " + f.crop.cropW + "x" + f.crop.cropH + "+" + f.crop.cropX + "+" + f.crop.cropY + " -resize " + f.width + "x" + f.height + " \\) -geometry +" + f.pos.left + "+" + f.pos.top + " -composite");
      }
      return results;
    })()).join(' ') + ' out.png';
  };

  addPx = function(obj) {
    var k, pxObj, v;
    pxObj = {};
    for (k in obj) {
      v = obj[k];
      pxObj[k] = v;
      if (v && 'number' === typeof v) {
        pxObj[k] += 'px';
      }
    }
    return pxObj;
  };

  loadTemplate = function(i) {
    var $cal, box, j, len, ref;
    metrics = {};
    $cal = $('#calendar').empty();
    ref = templates[i];
    for (j = 0, len = ref.length; j < len; j++) {
      box = ref[j];
      $('<div>').css(addPx(box)).appendTo($cal);
    }
    return $('#calendar > div').click(function(e) {
      var pos;
      e.preventDefault();
      if ($('body').hasClass('deleting')) {
        $(this).find('.cropFrame').remove();
        pos = $(this).position();
        delete metrics[[pos.left, pos.top]];
        return $('body').removeClass('deleting');
      } else if ($(this).find('img').length === 0) {
        selectedBox = this;
        return $('#file')[0].click();
      }
    });
  };

  $(function() {
    var i, j, len, template;
    $('#file').change(function() {
      var file, reader;
      file = this.files[0];
      if (!file) {
        return;
      }
      reader = new FileReader;
      reader.onloadend = function() {
        var $box, $img, height, key, pos, width;
        $box = $(selectedBox);
        width = $box.width();
        height = $box.height();
        $img = $('<img>').attr('src', reader.result).appendTo($box);
        pos = $box.position();
        key = [pos.left, pos.top].join();
        return $img.cropbox({
          width: width,
          height: height,
          zoom: 10,
          controls: false,
          showControls: 'never'
        }).on('cropbox', function(e, crop) {
          return metrics[key] = {
            crop: crop,
            width: width,
            height: height,
            pos: pos,
            name: file.name
          };
        });
      };
      return reader.readAsDataURL(file);
    });
    $('#delete').click(function() {
      return $('body').toggleClass('deleting');
    });
    $('#export').click(function() {
      return prompt('Paste this to your shell', generateConvert());
    });
    for (i = j = 0, len = templates.length; j < len; i = ++j) {
      template = templates[i];
      $('<option>').val(i).text("Template " + (i + 1)).appendTo('#template');
    }
    return $('#template').show().change(function() {
      return loadTemplate(this.selectedIndex);
    }).change();
  });

}).call(this);

//# sourceMappingURL=pan.js.map
